name: Deploy ETL Pipeline

on:
  push:
    branches:
      - main          # triggers on pushes to main branch
  workflow_dispatch:   # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform 

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.14.6"

      # Step 3: Configure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        
      - name: Import Step Function Role
        run: |
          terraform import aws_iam_role.step_function_role etl-step-function-role || true

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve

#      # Step 7: Trigger Glue Job
#      - name: Trigger Glue Job
#        run: |
#          echo "Starting Glue ETL job..."
#          aws glue start-job-run --job-name transaction-etl-job || echo "Job already running or exists, skipping."
#          
#      - name: Trigger ETL Workflow
#        run: |
#          # Get the Step Function ARN from Terraform outputs
#          STATE_MACHINE_ARN=$(terraform output -json state_machine_arn | tr -d '"')
#          
#          # Start the Step Function execution
#          aws stepfunctions start-execution \
#            --state-machine-arn "$STATE_MACHINE_ARN" \
#            --name "etl-execution-$(date +%s)" \
#            --region eu-north-1